# Build Options
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DEBUG_ENABLE = no
DEBUG_MATRIX = no

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGB_MATRIX_ENABLE = yes
NKRO_ENABLE = no
DIP_SWITCH_ENABLE = no
